### ISSUE TITLE
Application fails to launch

### ISSUE THREAD

**Issue by warrenrentlytics** [schrum2/CPPNArtEvolution#1]
I cloned the repo and ran the command that corresponds to `Launch-3DAnimationBreeder.bat` on macOS High Sierra:

```
$ java -jar CPPNArtEvolution.jar runNumber:0 randomSeed:0 base:objectanimationbreeder task:edu.nalAnimationBreeder-Run saveTo:Run maxGens:500 saveInteractiveSelections:false simplifiedInteractiveInterface:false saveAllChampions:false
Integer value "runNumber" set to "0"
Integer value "randomSeed" set to "0"
String value "base" set to "objectanimationbreeder"
Class value "task" set to "edu.southwestern.tasks.interactive.objectbreeder.ThreeDimensionalAnimationBreederTask"
String value "log" set to "ThreeDimensionalAnimationBreeder-Run"
String value "saveTo" set to "Run"
Integer value "maxGens" set to "500"
Boolean value "saveInteractiveSelections" set to "false"
Boolean value "simplifiedInteractiveInterface" set to "false"
Boolean value "saveAllChampions" set to "false"
File exists? objectanimationbreeder/Run0/ThreeDimensionalAnimationBreeder-Run0_parameters.txt
Made directory: objectanimationbreeder
Reset random seed to: 0
Run:
Init Genotype Ids
Constructor: public edu.southwestern.util.random.GaussianGenerator()
Constructor: public edu.southwestern.evolution.crossover.network.TWEANNCrossover()
Set Task
Constructor: public edu.southwestern.tasks.interactive.objectbreeder.ThreeDimensionalAnimationBreederTask() throws java.lang.IllegalAccessException
Load task: edu.southwestern.tasks.interactive.objectbreeder.ThreeDimensionalAnimationBreederTask@619713e5
set up Interactive Evolution Task
Networks will have 6 inputs and 7 outputs.
Use meta-heuristics?
Create EA
Constructor: public edu.southwestern.evolution.selectiveBreeding.SelectiveBreedingEA()
Example genotype
Constructor: public edu.southwestern.evolution.genotypes.TWEANNGenotype()
Init archetype from genotype example
Saving archetype
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NoClassDefFoundError: wox/serial/Easy
	at edu.southwestern.evolution.EvolutionaryHistory.saveArchetype(EvolutionaryHistory.java:282)
	at edu.southwestern.evolution.EvolutionaryHistory.initArchetype(EvolutionaryHistory.java:223)
	at edu.southwestern.evolution.EvolutionaryHistory.initArchetype(EvolutionaryHistory.java:192)
	at edu.southwestern.evolution.EvolutionaryHistory.initArchetype(EvolutionaryHistory.java:176)
	at edu.southwestern.MMNEAT.MMNEAT.setupTWEANNGenotypeDataTracking(MMNEAT.java:146)
	at edu.southwestern.MMNEAT.MMNEAT.loadClasses(MMNEAT.java:326)
	at edu.southwestern.MMNEAT.MMNEAT.run(MMNEAT.java:362)
	at edu.southwestern.MMNEAT.MMNEAT.evolutionaryRun(MMNEAT.java:477)
	at edu.southwestern.MMNEAT.MMNEAT.main(MMNEAT.java:448)
	... 5 more
Caused by: java.lang.ClassNotFoundException: wox.serial.Easy
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 14 more
```

```
$ java -version
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```

**Comment by warrenrentlytics** [comment]
Judging from https://github.com/schrum2/CPPNArtEvolution/blob/master/.classpath, it would appear there are external dependencies not being built into the JAR in the repository.

Perhaps a maven script could be set up to produce an uber JAR containing all dependencies. https://maven.apache.org/plugins/maven-shade-plugin/

**Comment by schrum2** [comment]
This repo is actually a much simplified version of the MM-NEAT repo ( https://github.com/schrum2/MM-NEAT ) which actually is Maven based. However, there is a LOT of other content there and not everyone wants to Maven compile such a massive project just to get access to one small piece. In fact, I specifically made this repo this way so that people would not have to deal with Maven. However, all CPPN art evolution code is in the Maven-based MM-NEAT project, including some improvements as well as new interactive evolution scenarios (such as GAN-based evolution of Mario levels).

However, I think you should be able to get this repo to work fairly easily as well. It's unfortunate that the provided jar file does not work on Mac. It might honestly be a Java version issue ... try going back to Java 9 or 8. 

Still, the wox libraries are included in the repo if you want/need to recompile. This is the jar in question: https://github.com/schrum2/CPPNArtEvolution/blob/master/lib/woxser-1.0.jar . In fact, all of the libraries you need should be in https://github.com/schrum2/CPPNArtEvolution/tree/master/lib . If you simply open the project in Eclipse you can directly run the class https://github.com/schrum2/CPPNArtEvolution/blob/master/src/edu/southwestern/tasks/interactive/objectbreeder/ThreeDimensionalObjectBreederTask.java to interact with the system.

Please let me know if you are able to get this running, and thanks for your interest.
